language: node_js
node_js:
  - '6'
before_script:
  - npm prune
after_success:
  - git config --global user.name "Travis-CI"
    git config --global user.email "travis@example.com"
    node scripts/deploy.js
branches:
  only:
    - master
